# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZgoxpFZLQQefrnGRlvYI9X8YyxFWcyfF
"""

import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


vowelDF = pd.read_csv("Vowel_Data.csv", sep=",", header=0, encoding="UTF-8")

vowelDF.shape


vowelDF.head()


X = vowelDF.iloc[:, 3:-1]
y = vowelDF.iloc[:, -1]


lb = LabelBinarizer().fit(y)
yBin = lb.transform(y)


X.head(2)

X_train, X_test, y_train, y_test = train_test_split(X, yBin, train_size=0.8, test_size=0.2,
                                                    shuffle=True, stratify=y, random_state=42)

knn = KNeighborsClassifier(n_neighbors=2, n_jobs=-1)
knn.fit(X_train, y_train)


y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)


y_test[8]


lb.inverse_transform(y_test[8].reshape(1, -1))


pred = knn.predict(X_test.iloc[8].values.reshape(1,-1))


pred

lb.inverse_transform(pred)


knn.predict_proba(X_test.iloc[8].values.reshape(1,-1))

n = list(range(1,5))
acc = []

for i in n:
    knn = KNeighborsClassifier(n_neighbors=i, n_jobs=-1)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    acc.append(accuracy)

acc

import matplotlib.pyplot as plt
desc = plt
desc.scatter(n, acc)
desc.show()